config/routes.rb
LocateMyStickers::Application.routes.draw do
  
  resources :tags


  # Root  #
  ######

  root :to => 'map#map'


  # Users   #
  #######
    
  match '/users/create_user', :to => 'users#create_user'
  match '/users/delete_user', :to => 'users#delete_user'
  match '/users/admins', to: 'users#admins'
  match '/users/count', to: 'users#count'

  match '/users/:id/initialize_data', to: 'users#initialize_data'
  match '/users/:id/updateddata',  to: 'users#updated_data'
  match '/users/:id/getstickers',  to: 'stickers#get_stickers'
  match '/users/:id/friends',  to: 'users#friends', only: [:index]
  match '/users/:id/add_friend',  to: 'users#add_friend'
  match '/users/:id/remove_friend',  to: 'users#remove_friend'
  match '/users/:id/is_friend',  to: 'users#is_friend'
  match '/users/:id/update_user', :to => 'users#update_user'
  match '/users/:id/statistics', :to => 'users#statistics'
  match '/create_message', :to => 'messages#create_message'

  
  # Notifications #
  ##########

  match '/users/:id/new_notifications', :to => 'users#new_notifications'
  match '/users/:id/old_notifications', :to => 'users#old_notifications'

  
  # Stickers  #
  ########
  
  match '/users/:user_id/stickers/:id/update_locations', to: 'stickers#update_locations', as: 'update_user_sticker_locations'
  match '/users/:user_id/stickers/count', to: 'stickers#count'
  match '/users/:user_id/stickers/locations', to: 'stickers#locations'
  match '/users/:user_id/stickers/:id/locations_for', to: 'stickers#locations_for'
  match '/users/:id/empty_stickers_locations', :to => 'users#empty_stickers_locations'
  match '/stickers/:id/possessor', :to => 'stickers#possessor'
  match '/update_sticker', :to => 'stickers#update'
  match '/delete_sticker', :to => 'stickers#destroy'



  # Locations  #
  #########
  
  match '/live_locations', :to => "locations#live_locations"
  match '/users/:user_id/stickers/:sticker_id/locations/count', to: 'locations#count'
  match '/users/:user_id/stickers/:id/lastlocationaddress', to: 'stickers#last_location_address'
  match '/users/:user_id/stickers/:id/last_location', to: 'stickers#last_location'
  match '/users/:user_id/stickers/:id/share_with_user', to: 'stickers#share_with_user'


  # Zones  #
  #######

    match '/users/:user_id/stickers/:sticker_id/zones/:id/fence', to: 'zones#fence'

  # Histories (events)   #
  ##############

  match '/histories/:id/confirm', :to => 'histories#confirm'


  # Ressources #
  ##########
  
  resources :users do
    resources :conversations do
      resources :messages, :users
    end
    resources :messages, :histories
    resources :stickers do
      resources :sticker_configurations
      resources :histories, :locations
      resources :zones do
        resources :zone_locations
      end
      match '/minimap', to: 'stickers#minimap'
    end

    member do
      get :followed_stickers, :shared_stickers
      get :following, :followers
    end
  end

  resources :friendships,   only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  resources :messages
  resources :histories
  resources :posts


  # Sessions #
  ########

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'#, via: :delete


  # Static pages #
  ##########

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/stats', to: 'static_pages#stats'
  match '/news', to: 'posts#news'
  match '/documentation', to: 'static_pages#documentation'


  # Admin  #
  #######

  match '/admin/routes', to: 'administration#routes'
  match '/admin/update_route/:id', to: 'administration#update_route', as: 'update_route'
  match '/admin/developer_guide', to: 'administration#developer_guide'
  match '/admin/launch_simulation', to: 'administration#launch_simulation'
  match '/admin/simulator', to: 'administration#simulator'
  match '/admin/example_comands', to: 'administration#example_comands'
  match '/admin', to: 'administration#admin'


  # Global Ressource #
  #############

  match '/friendships', to: 'friendships#destroy', via: :delete
  match '/stickers', to: 'stickers#all_stickers'
  match '/locations', to: 'locations#all_locations'
  match '/conversations', to: 'conversations#all_conversations'
  match '/zones', to: 'zones#all_zones'
  

  # Map   #
  ######

  match '/map', to: 'map#map'
  
end

app/models/message.rb
# == Schema Information
#
# Table name: messages
#
#  id           :integer          not null, primary key
#  user_id      :integer
#  from_user_id :integer
#  subject      :string(255)
#  content      :string(255)
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Message < ActiveRecord::Base
  attr_accessible :content, :from_user_id, :subject, :user_id, :created_at, :id, :updated_at

  belongs_to :user
  belongs_to :from_user, class_name: 'User'

  validates :subject, :presence => true
  validates :content, :presence => true

  def self.count_sent_messages(user, messages)
  	messages.select{ |m| m.from_user_id == user.id }.count
  end

  def self.count_received_messages(user, messages)
  	messages.select{ |m| m.user_id == user.id }.count
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  include ApplicationHelper
  before_filter :column_names
  #before_filter :login_or_oauth_required, except: :create
  helper_method :sort_column, :sort_direction
  before_filter :get_user

  # GET /messages
  # GET /messages.json
  def index
    if (params.has_key?(:user_id) && !params[:user_id].nil?)
      @messages = (User.sent_messages(@user) + @user.messages)
    else
      @messages = Message.all
    end
    @messages = @messages.sort_by { |m| m.created_at }.reverse
    @conversations = @messages.group_by { |message| message.subject }
    if (params.has_key?(:user_id) && !params[:user_id].nil?)
      @title = User.find(params[:user_id]).name + "'s messages"
    else
      @title = "Messages"
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @conversations }
    end
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
    redirect_to user_messages_path(params[:user_id])
  end

  # GET /messages/new
  # GET /messages/new.json
  def new
    @message = Message.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @message }
    end
  end

  # GET /messages/1/edit
  def edit
    @message = Message.find(params[:id])
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(params[:message])

    # Set the message subject to recover conversations
    if (@message.from_user_id > 0)
      set_message_subject
    end

    respond_to do |format|
      if @message.save
        format.html { 
          if (@message.from_user_id > 0)
            flash[:success] = 'Message was successfully sent.'
            path = user_messages_path(current_user) + "#message-#{@message.id}"
            redirect_to path
          else # Message comes from the 'contact us' form
            message_from_contact_form
          end
        }
        format.json { render json: @message, status: :created, location: @message }
      else
        format.html { render action: "new" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /messages/1
  # PUT /messages/1.json
  def update
    @message = Message.find(params[:id])

    respond_to do |format|
      if @message.update_attributes(params[:message])
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message = Message.find(params[:id])
    @message.destroy

    respond_to do |format|
      format.html { redirect_to messages_url }
      format.json { head :no_content }
    end
  end

  private

    def column_names
      @column_names = Message.column_names
    end

    def get_user
      if (params.has_key?(:user_id) && !params[:user_id].nil?)
        @user = User.find(params[:user_id])
      else
        @user = current_user
      end
    end

    def set_message_subject
      if (@message.from_user_id == 0)
        @message.subject = "Through contact form"
      else
        other_message = Message.find_by_subject(User.find(@message.user_id).name + " " + User.find(@message.from_user_id).name)
        if (other_message.nil?)
          other_message = Message.find_by_subject(User.find(@message.from_user_id).name + " " + User.find(@message.user_id).name)
        end
        if (other_message.nil?)
          @subject = User.find(@message.from_user_id).name + " " + User.find(@message.user_id).name
        else
          @subject = other_message.subject
        end
        @message.subject = @subject
      end
    end

    def message_from_contact_form
      password = Digest::MD5::hexdigest(@message.subject)
      unknown_sender = User.create!(first_name: @message.subject,
                                   last_name: "(contact form)",
                                   email: @message.subject,
                                   password: password,
                                   password_confirmation: password,
                                   compteur: 0)
      if @message.update_attributes(from_user_id: unknown_sender.id)
        Emailer.welcome_email(User.first).deliver
        flash[:success] = 'Message was successfully sent. Thank you for your interest.'
        redirect_to root_path
      end
    end
end

app/helpers/messages_helper.rb
module MessagesHelper
	def get_message_subject(sender, receiver)
    other_message = Message.find_by_subject(sender.name + " " + receiver.name)
    if (other_message.nil?)
      other_message = Message.find_by_subject(receiver.name + " " + sender.name)
    end
    if (other_message.nil?)
      subject = sender.name + " " + receiver.name
    else
      subject = other_message.subject
    end
    subject
	end

  # Web service

  def create_ws_message(message)
    CLogger.debug 'create_ws_message: message:' + message.inspect.to_s
    web_service_url('create_message?' + ({
      'message[content]' => message['content'],
      'message[from_user_id]' => message['from_user_id'],
      'message[user_id]' => message['user_id'],
      'message[subject]' => message['subject'] }).to_param.to_s)
    update_or_create_message(message)
    CLogger.debug 'create_ws_message: @parsed_json:' + @parsed_json.to_s
    return Message.new(@parsed_json)
  end

  def get_ws_user_message(user_id, message_id)
    web_service_url('users/' + user_id.to_s + '/messages/' + message_id.to_s + '.json')
    get_url
    message = parse_message_from_parsed_json
    CLogger.info 'get_ws_user_message: got message: ' + message.inspect.to_s
    return message
  end

  def get_ws_user_messages(user_id)
    web_service_url('users/' + user_id.to_s + '/messages.json')
    get_url
    messages = parse_messages_from_parsed_json
    CLogger.info 'get_ws_user_messages: got messages: ' + messages.count.to_s
    return messages
  end

  def get_ws_all_messages(paginate = false, per_page = 10, page = 1)
    web_service_url('/messages.json')
    get_url
    messages = parse_messages_from_parsed_json(paginate, per_page, page)
    return messages
  end

  def update_or_create_message(message)
    CLogger.info('Started GET update_or_create_message ' + @data_url)
    url = URI.parse(@data_url)
    req = Net::HTTP::Get.new(url.to_s)
    res = Net::HTTP.start(url.host, url.port) { |http| http.request(req) }
    @parsed_json = ActiveSupport::JSON.decode(res.body)
    CLogger.info('Request returned ' + @parsed_json.to_s)
  end

  def parse_message_from_parsed_json
      message = Message.new(@parsed_json)
      message.id = @parsed_json['id']
      return message
  end

  def parse_messages_from_parsed_json(paginate = false, per_page = 10, page = 1)
    CLogger.info 'parse_messages_from_parsed_json: @parsed_json: ' + @parsed_json.to_s
    messages = Array.new
    @parsed_json.each do |message, r|
      m = Message.new(message)
      m.id = message['id']
      messages.push(m)
    end
    return messages
  end
end

app/views/messages/_contact_form.html.erb
<%= form_for(@message) do |f| %>
  <% if @message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% @message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Your email" %>
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, rows: 3, class: 'input-block-level', placeholder: "Please type your message here." %>
  </div>
  <%= f.hidden_field :from_user_id, :value => 0 %>
  <%= f.hidden_field :user_id, :value => 1 %>
  <div class="actions">
    <%= f.submit 'Send', class: 'btn-default btn-primary' %>
    <span class="help-inline">An e-mail will be sent to the developers in charge of the project.</span>
  </div>
<% end %>

app/views/messages/_conversation.html.erb

<%
	if with_user == current_user
		tmp = from_user
		from_user = current_user
		with_user = tmp
	end
%>

<div class="well well-padding paper-shadow">
  <div class="accordion-heading">
		<h4>
      <a style="display:inline;" class="accordion-toggle" data-toggle="collapse" data-parent=".accordion" href="#collapseOne<%= conversation.first.id %>">
        <i class="icon-plus"></i>
      </a>
      <% if from_user == current_user %>
      <%= link_to 'Me', user_path(from_user) %>
      <% else %>
      <%= link_to from_user.name, user_path(from_user) %>
      <% end %>
       and <%= link_to with_user.name, user_path(with_user) %>
    </h4>
  </div>
  <blockquote id="conversation-with-<%= with_user.id %>">
  	<%
  		conversation = conversation.reverse 
  		conversation.each do |message| %>
  	  <%= render 'message_block', message: message %>
  	<% end %>
  </blockquote>
  <div style="border-bottom:1px solid #f5f5f5; height:1px; width:100%; padding-right: 20px;margin-bottom:20px;"></div>
  <%= render 'form', from: from_user.id, to: with_user.id, conversation: conversation %>
</div>


app/views/messages/_form.html.erb
<%= form_for(current_user.messages.build(:from_user_id => from, :user_id => to)) do |f| %>
  <%= f.text_area :content, rows: 2, style: "max-width: 600px;max-height:150px;" %>
  <%= f.hidden_field :from_user_id, :value => from %>
  <%= f.hidden_field :user_id, :value => to %>
  <div class="actions">
    <%= f.submit 'Send', class: 'btn' %>
  </div>
<% end %>

app/views/messages/_message_block.html.erb
 <div>

<% if (!message.from_user_id.nil? && message.from_user_id != 0)
    user = User.find(message.from_user_id)
  end
  unless user.nil?
 %>
  <b>
    <a href="<%= user_path(user) %>">
      <% if (user == current_user) %>
        Me:
      <% else %>
        <%= user.name %>:
      <% end %>
    </a>
  </b>
<% else %>
  <b>
    Unknown user:
  </b>
<% end %>
<%= message.content %>
<small class="muted pull-right">
  At <%= message.created_at %> 
</small>
</div>

app/views/messages/_messages.html.erb
<div id="messages">
  <% @conversations.each do |subject, conversation| %>
	<%
			from_user = User.find(conversation.first.from_user_id)
			with_user = User.find(conversation.first.user_id)
	%>
    <%= render 'conversation', subject: subject, conversation: conversation, from_user: from_user, with_user: with_user %>
  <% end %>
</div>

app/views/messages/edit.html.erb
<h1>Editing message</h1>

<%= render 'form' %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<% provide(:title, @title) %>

<div class="container-fluid page-content">
  <%= render 'shared/server_stats_header' %>

  <div id="messages-list" style="position:relative;top:-250px"></div>
  <h1><%= @title %></h1><br/>
  <%= render 'messages', messages: @messages %>
</div>

<!-- Sidebar Fixed left -->
<% content_for :sidebar do %>
  <%= render 'users/friends', user: @user %>
  <h3>Navigate</h3>
  <ul id="sidebar-nav" class="nav nav-list affix" data-offset-top="200px">
    <li><a href="#messages-list" class="messages-list">Messages list</a></li>
    <% @conversations.each do |subject, conversation| %>
	    <li><a href="#collapseOne<%= conversation.first.id %>" class="messages-list">
	    	<%= subject.split.delete_if{|x| @user.first_name == x || @user.last_name == x}.join(' ') %></a></li>
    <% end %>
  </ul>
<% end %>

app/views/messages/new.html.erb
<% provide(:title, @title) %>

<div class="container-fluid page-content">
  <%= render 'shared/server_stats_header' %>
  <div id="messages-list" style="position:relative;top:-250px"></div>
  <h1><%= @title %></h1>
  <%= render 'form', from: current_user.id, to: params[:user_id] %>
</div>

<!-- Sidebar Fixed left -->
<% content_for :sidebar do %>
  <%= render 'users/friends', user: @user %>
<% end %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @message.user_id %>
</p>

<p>
  <b>From user:</b>
  <%= @message.from_user_id %>
</p>

<p>
  <b>Subject:</b>
  <%= @message.subject %>
</p>

<p>
  <b>Content:</b>
  <%= @message.content %>
</p>


<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>