config/routes.rb
LocateMyStickers::Application.routes.draw do
  
  resources :tags


  # Root  #
  ######

  root :to => 'map#map'


  # Users   #
  #######
    
  match '/users/create_user', :to => 'users#create_user'
  match '/users/delete_user', :to => 'users#delete_user'
  match '/users/admins', to: 'users#admins'
  match '/users/count', to: 'users#count'

  match '/users/:id/initialize_data', to: 'users#initialize_data'
  match '/users/:id/updateddata',  to: 'users#updated_data'
  match '/users/:id/getstickers',  to: 'stickers#get_stickers'
  match '/users/:id/friends',  to: 'users#friends', only: [:index]
  match '/users/:id/add_friend',  to: 'users#add_friend'
  match '/users/:id/remove_friend',  to: 'users#remove_friend'
  match '/users/:id/is_friend',  to: 'users#is_friend'
  match '/users/:id/update_user', :to => 'users#update_user'
  match '/users/:id/statistics', :to => 'users#statistics'
  match '/create_message', :to => 'messages#create_message'

  
  # Notifications #
  ##########

  match '/users/:id/new_notifications', :to => 'users#new_notifications'
  match '/users/:id/old_notifications', :to => 'users#old_notifications'

  
  # Stickers  #
  ########
  
  match '/users/:user_id/stickers/:id/update_locations', to: 'stickers#update_locations', as: 'update_user_sticker_locations'
  match '/users/:user_id/stickers/count', to: 'stickers#count'
  match '/users/:user_id/stickers/locations', to: 'stickers#locations'
  match '/users/:user_id/stickers/:id/locations_for', to: 'stickers#locations_for'
  match '/users/:id/empty_stickers_locations', :to => 'users#empty_stickers_locations'
  match '/stickers/:id/possessor', :to => 'stickers#possessor'
  match '/update_sticker', :to => 'stickers#update'
  match '/delete_sticker', :to => 'stickers#destroy'



  # Locations  #
  #########
  
  match '/live_locations', :to => "locations#live_locations"
  match '/users/:user_id/stickers/:sticker_id/locations/count', to: 'locations#count'
  match '/users/:user_id/stickers/:id/lastlocationaddress', to: 'stickers#last_location_address'
  match '/users/:user_id/stickers/:id/last_location', to: 'stickers#last_location'
  match '/users/:user_id/stickers/:id/share_with_user', to: 'stickers#share_with_user'


  # Zones  #
  #######

    match '/users/:user_id/stickers/:sticker_id/zones/:id/fence', to: 'zones#fence'

  # Histories (events)   #
  ##############

  match '/histories/:id/confirm', :to => 'histories#confirm'


  # Ressources #
  ##########
  
  resources :users do
    resources :conversations do
      resources :messages, :users
    end
    resources :messages, :histories
    resources :stickers do
      resources :sticker_configurations
      resources :histories, :locations
      resources :zones do
        resources :zone_locations
      end
      match '/minimap', to: 'stickers#minimap'
    end

    member do
      get :followed_stickers, :shared_stickers
      get :following, :followers
    end
  end

  resources :friendships,   only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  resources :messages
  resources :histories
  resources :posts


  # Sessions #
  ########

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'#, via: :delete


  # Static pages #
  ##########

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/stats', to: 'static_pages#stats'
  match '/news', to: 'posts#news'
  match '/documentation', to: 'static_pages#documentation'


  # Admin  #
  #######

  match '/admin/routes', to: 'administration#routes'
  match '/admin/update_route/:id', to: 'administration#update_route', as: 'update_route'
  match '/admin/developer_guide', to: 'administration#developer_guide'
  match '/admin/launch_simulation', to: 'administration#launch_simulation'
  match '/admin/simulator', to: 'administration#simulator'
  match '/admin/example_comands', to: 'administration#example_comands'
  match '/admin', to: 'administration#admin'


  # Global Ressource #
  #############

  match '/friendships', to: 'friendships#destroy', via: :delete
  match '/stickers', to: 'stickers#all_stickers'
  match '/locations', to: 'locations#all_locations'
  match '/conversations', to: 'conversations#all_conversations'
  match '/zones', to: 'zones#all_zones'
  

  # Map   #
  ######

  match '/map', to: 'map#map'
  
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
	include ApplicationHelper

	def admin
	end

	def developer_guide
	end

	def simulator
		@sticker = current_user.stickers.first
		@simulation = Simulation.create!(user_id: current_user.id, sticker_id: @sticker.id, locations_sent: 0, description: "#{current_user.name}: Simulation " + Simulation.count.to_s)
	end

	def launch_simulation
		@simulation = Simulation.find(params[:simulation_id])
		@sticker = Sticker.find(@simulation.sticker_id)
		# system("pwd >> launch_simulation");
		#system("ruby simulate_stickers.rb");
		respond_to do |format|
			format.js
		end
	end

	def routes

		if params[:update] == 'true'
			file_routes = Array.new
			puts 'bundle exec rake routes > routes'
			system 'bundle exec rake routes > routes'
			File.open("routes", "r") {|io| io.read}.split(/\r?\n/).each { |l| file_routes << l.split(' ') };

			AppRoute.destroy_all

			file_routes.each do |route|
				name = 'Default name'
				method = 'Default method'
				path = 'Default path'
				action = 'Default action'
				route.each do |r|
					if r.include?('#')
						action = r
					elsif r.include?('_')
						name = r
					elsif r.include?('/')
						path = r
					elsif r.include?('GET')
						method = r
					end
				end
				AppRoute.create!({
					title: 'Title ' + AppRoute.count.to_s,
					name: name,
					path: path,
					method: method,
					action: action
				})
			end
		end

		@routes = AppRoute.all
	end

	def update_route
		route = AppRoute.find(params[:id])
		route.update_attributes(params[:app_route])
		
		respond_to do |format|
			format.js
		end
	end

	def example_comands
		@heroku_comands = Array.new
		File.open("example_heroku_comands", "r") {|io| io.read}.split(/\r?\n/).each { |l| @heroku_comands << l };
		@rake_comands = Array.new
		File.open("example_rake_comands", "r") {|io| io.read}.split(/\r?\n/).each { |l| @rake_comands << l };
		@rails_comands = Array.new
		File.open("example_rails_comands", "r") {|io| io.read}.split(/\r?\n/).each { |l| @rails_comands << l };
		@git_comands = Array.new
		File.open("example_git_comands", "r") {|io| io.read}.split(/\r?\n/).each { |l| @git_comands << l };
	end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administration/admin.html.erb
<% provide(:title, 'Administration pannel') %>
<div class="planet"></div>
<div style="opacity:.9; width:610px; margin:0 auto;">
	<div class="well paper-shadow" style="margin-top:100px;">
		<h1>Administration pannel</h1><br/>
		<div class="row">
			<div class="col-md-3">
				<p class="lead">
					Browse !
				</p>
				<a href="<%= users_path %>"><h4>Users</h4></a>
				<a href="<%= stickers_path %>"><h4>Stickers</h4></a>
				<a href="<%= locations_path %>"><h4>Locations</h4></a>
				<a href="<%= messages_path %>"><h4>Messages</h4></a>
				<a href="<%= histories_path %>"><h4>Events</h4></a>
			</div>
			<div class="col-md-9">
				<p class="lead">
					Managing tools for our awesome app !
				</p>
				<a href="<%= posts_path %>"><h4>News feed</h4></a>
				<p>Publish articles to communicate with the public.</p>
				<a href="/admin/developer_guide"><h4>Developer guide</h4></a>
				<p>Here is some help for whoever wants to help on the development of this web application.</p>
				<a href="/admin/example_comands"><h4>Example commands</h4></a>
				<p>Some example commands to develop on our application.</p>
				<a href="/admin/simulator"><h4>Stickers simulator 3000</h4></a>
				<p>Simulates activity of multiple stickers. Try to make our app crash if you dare!</p>
				<a href="/admin/routes"><h4>Application routes</h4></a>
				<p>Generates routes for the app, for you to explore :)</p>
			</div>
		</div>
	</div>
</div>

app/views/administration/developer_guide.html.erb
<% provide(:title, 'Developer guide') %>
<div style="background-image: url('/assets/contact-background.jpg');position:absolute;right:0;left:0;bottom:0;top:0">
</div>
<div style="opacity:.9; width:910px; margin:0 auto;">
	<div class="well paper-shadow" style="margin-top:100px;">
		
		<ol class="breadcrumb">
			<li><%= link_to 'Administration', '/admin' %> /</li>
			<li class="active">Developper Guide</li>
		</ol>

		<h2>Welcome, LMS developer</h2>
		<p>
			Here are some usefull notes for developping on the web application of our solution.
			<ol>
				<li><%= link_to 'Up and running', '#up-and-running' %></li>
			</ol>
			Please contact Benoit Liabastre for more information.
		</p>
		
		<div id="up-and-running" class="well paper-shadow" style="margin-top:30px;">
			<h3>Up and running</h3>
			<p>
				For this guide, I assume you already have Ruby, Ruby on Rails, and RVM installed on your machine as explained in <%= link_to 'this tutorial', 'http://www.rackspace.com/blog/installing-rails-on-a-mac/' %> (stop before "ImageMagik" chapter, and ignore Xquartz installatio")
				<ol>
					<li>
						<b>Check out the source</b>:
						<code>git cone git@locatemystickers.com:development/web-service.git</code><br/>
						<code>cd web-service</code><br/><br/>
						In this folder, there is both the source for the web service and web application.<br/>
						Since they use all the same models, I did that to replicate as less code as possible.
						To be sure you develop on the web application, check:
						<ul>
							<li>
								That <code>Rails.configuration.app_scope = "webapp"</code> is set to "webapp" (and not "service") in app/config/environment.rb.
								This variable is used in the code (eg. some helpers) to know wich app is running.
							</li>
							<li>
								That <code>#scope :module => "service" do</code> and its closing tag are correctly commented in app/config/routes.rb
								When this is not commented, the routes are set to use web service controllers in app/controlers/service/. Else, app/controlers/ are used.
								Never edit app/controllers/service/* when you develop on the web application.
							</li>
						</ul>
					</li><br/>
					<li>
						<b>Install the app</b>: <code>bundle install --without production test</code><br/>
						This installs the Gems contained in your Gemfile and their dependances.
					</li><br/>
					<li>
						<b>Migrate the database</b>: <code>bundle exec rake db:migrate</code><br/>
						This creates the database of the app, using the ActiveRecord ORM. Rake executes all the migrations contained in db/migrate/.
					</li><br/>
					<li>
						<b>Run the application</b>: <code>rails s</code><br/>
						This runs the rails server of the application on port 3000. You can now see the app on <%= link_to 'localhost:3000', 'http://localhost:3000/' %>
						Note: if you want to run multiple Ruby on Rails applications on your machine, use <code>rails s -p $port</code>.
					</li>
				</ol>
			</p>
		</div>
	</div>
</div>

app/views/administration/example_comands.html.erb
<% provide(:title, 'Example comands') %>
<div style="opacity:.9; width:1024px; margin:0 auto;">
  <div class="well" style="margin-top:100px;">
    <h1>Example comands</h1><br/>
    <div class="row">
      <div class="col-md-12">

<div class="panel-group" id="accordion" class="paper-shadow">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="input-prepend">
          <span class="add-on">
            <a style="display:inline;" class="accordion-toggle btn-default btn-default dropdown-toggle btn-sm" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
        <span class="lead">
          Some heroku examples
        </span>
                  <span class="caret"></span>
            </a>
          </span>

        </div>
      </div>
      <div class="panel-collapse">
        <div class="panel-body">

        <table class="table table-hover">
          <% @heroku_comands.each do |comand| %>
            <tr>
              <td><%= comand %></td>
            </tr>
          <% end %>
        </table>
        </div>
      </div>
    </div>
  </div>


<div class="panel-group" id="accordion" class="paper-shadow">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="input-prepend">
          <span class="add-on">
            <a style="display:inline;" class="accordion-toggle btn-default btn-default dropdown-toggle btn-sm" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
        <span class="lead">
          Some rake examples
        </span>
                  <span class="caret"></span>
            </a>
          </span>

        </div>
      </div>
      <div class="panel-collapse">
        <div class="panel-body">

        <table class="table table-hover">
          <% @rake_comands.each do |comand| %>
            <tr>
              <td><%= comand %></td>
            </tr>
          <% end %>
        </table>
        </div>
      </div>
    </div>
  </div>


<div class="panel-group" id="accordion" class="paper-shadow">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="input-prepend">
          <span class="add-on">
            <a style="display:inline;" class="accordion-toggle btn-default btn-default dropdown-toggle btn-sm" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
        <span class="lead">
          Some rails examples
        </span>
                  <span class="caret"></span>
            </a>
          </span>

        </div>
      </div>
      <div class="panel-collapse">
        <div class="panel-body">

        <table class="table table-hover">
          <% @rails_comands.each do |comand| %>
            <tr>
              <td><%= comand %></td>
            </tr>
          <% end %>
        </table>
        </div>
      </div>
    </div>
  </div>


<div class="panel-group" id="accordion" class="paper-shadow">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="input-prepend">
          <span class="add-on">
            <a style="display:inline;" class="accordion-toggle btn-default btn-default dropdown-toggle btn-sm" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
        <span class="lead">
          Some git examples
        </span>
                  <span class="caret"></span>
            </a>
          </span>

        </div>
      </div>
      <div class="panel-collapse">
        <div class="panel-body">

        <table class="table table-hover">
          <% @git_comands.each do |comand| %>
            <tr>
              <td><%= comand %></td>
            </tr>
          <% end %>
        </table>
        </div>
      </div>
    </div>
  </div>

      </div>
    </div>
  </div>
</div>

app/views/administration/launch_simulation.js.erb
for ( var i = 0; i < 180; i++ ) {
  console.log(i);
  $.post( "/users/<%= @sticker.user.id %>/stickers/<%= @sticker.id %>/locations.json", { location: { latitude: i, longitude: i } });
}

app/views/administration/routes.haml
.content-center
  .box
    %h1 API Routes
  - @routes.each do |route|
    = render 'routes/route', route: route

app/views/administration/simulator.haml
- provide(:title, 'Administration pannel')
.planet
.content-center
  .box
    %ol.breadcrumb
      %li= link_to 'Administration', '/admin'
      %li.active Simulator 3000
    %h2 Stickers simulator 3000
    %p
      "Simulation #{@simulation.description} running with sticker #{ link_to @sticker.name , user_sticker_path(@sticker.user_id, @sticker.id) }
      = form_tag "/admin/launch_simulation?simulation_id=" + @simulation.id.to_s, :method => 'get', remote: true do |f|
        = submit_tag 'Launch', class: 'btn-default btn-primary center'

app/views/administration/update_route.js.erb
alert("Route updated!");