config/routes.rb
LocateMyStickers::Application.routes.draw do
  
  resources :tags


  # Root  #
  ######

  root :to => 'map#map'


  # Users   #
  #######
    
  match '/users/create_user', :to => 'users#create_user'
  match '/users/delete_user', :to => 'users#delete_user'
  match '/users/admins', to: 'users#admins'
  match '/users/count', to: 'users#count'

  match '/users/:id/initialize_data', to: 'users#initialize_data'
  match '/users/:id/updateddata',  to: 'users#updated_data'
  match '/users/:id/getstickers',  to: 'stickers#get_stickers'
  match '/users/:id/friends',  to: 'users#friends', only: [:index]
  match '/users/:id/add_friend',  to: 'users#add_friend'
  match '/users/:id/remove_friend',  to: 'users#remove_friend'
  match '/users/:id/is_friend',  to: 'users#is_friend'
  match '/users/:id/update_user', :to => 'users#update_user'
  match '/users/:id/statistics', :to => 'users#statistics'
  match '/create_message', :to => 'messages#create_message'

  
  # Notifications #
  ##########

  match '/users/:id/new_notifications', :to => 'users#new_notifications'
  match '/users/:id/old_notifications', :to => 'users#old_notifications'

  
  # Stickers  #
  ########
  
  match '/users/:user_id/stickers/:id/update_locations', to: 'stickers#update_locations', as: 'update_user_sticker_locations'
  match '/users/:user_id/stickers/count', to: 'stickers#count'
  match '/users/:user_id/stickers/locations', to: 'stickers#locations'
  match '/users/:user_id/stickers/:id/locations_for', to: 'stickers#locations_for'
  match '/users/:id/empty_stickers_locations', :to => 'users#empty_stickers_locations'
  match '/stickers/:id/possessor', :to => 'stickers#possessor'
  match '/update_sticker', :to => 'stickers#update'
  match '/delete_sticker', :to => 'stickers#destroy'



  # Locations  #
  #########
  
  match '/live_locations', :to => "locations#live_locations"
  match '/users/:user_id/stickers/:sticker_id/locations/count', to: 'locations#count'
  match '/users/:user_id/stickers/:id/lastlocationaddress', to: 'stickers#last_location_address'
  match '/users/:user_id/stickers/:id/last_location', to: 'stickers#last_location'
  match '/users/:user_id/stickers/:id/share_with_user', to: 'stickers#share_with_user'


  # Zones  #
  #######

    match '/users/:user_id/stickers/:sticker_id/zones/:id/fence', to: 'zones#fence'

  # Histories (events)   #
  ##############

  match '/histories/:id/confirm', :to => 'histories#confirm'


  # Ressources #
  ##########
  
  resources :users do
    resources :conversations do
      resources :messages, :users
    end
    resources :messages, :histories
    resources :stickers do
      resources :sticker_configurations
      resources :histories, :locations
      resources :zones do
        resources :zone_locations
      end
      match '/minimap', to: 'stickers#minimap'
    end

    member do
      get :followed_stickers, :shared_stickers
      get :following, :followers
    end
  end

  resources :friendships,   only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :sessions,      only: [:new, :create, :destroy]
  resources :messages
  resources :histories
  resources :posts


  # Sessions #
  ########

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'#, via: :delete


  # Static pages #
  ##########

  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'
  match '/stats', to: 'static_pages#stats'
  match '/news', to: 'posts#news'
  match '/documentation', to: 'static_pages#documentation'


  # Admin  #
  #######

  match '/admin/routes', to: 'administration#routes'
  match '/admin/update_route/:id', to: 'administration#update_route', as: 'update_route'
  match '/admin/developer_guide', to: 'administration#developer_guide'
  match '/admin/launch_simulation', to: 'administration#launch_simulation'
  match '/admin/simulator', to: 'administration#simulator'
  match '/admin/example_comands', to: 'administration#example_comands'
  match '/admin', to: 'administration#admin'


  # Global Ressource #
  #############

  match '/friendships', to: 'friendships#destroy', via: :delete
  match '/stickers', to: 'stickers#all_stickers'
  match '/locations', to: 'locations#all_locations'
  match '/conversations', to: 'conversations#all_conversations'
  match '/zones', to: 'zones#all_zones'
  

  # Map   #
  ######

  match '/map', to: 'map#map'
  
end

app/models/history.rb
# == Schema Information
#
# Table name: histories
#
#  id                     :integer          not null, primary key
#  subject                :string(255)
#  operation              :string(255)
#  user_id                :integer          default(0)
#  sticker_id             :integer          default(0)
#  location_id            :integer          default(0)
#  message_id             :integer          default(0)
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  notification_level     :integer          default(0)
#  notify                 :integer          default(0)
#  notification_confirmed :integer          default(0)
#

class History < ActiveRecord::Base
  attr_accessible :subject, :operation, :notification_confirmed, :created_at, :id, :location_id, :message_id, :notification_level, :notify, :sticker_id, :updated_at, :user_id

  belongs_to :user
  belongs_to :sticker
  belongs_to :location
  belongs_to :message

  after_create :broadcast
    
  def self.search(search, column = 'subject')
    if search
      where("#{column} LIKE ?", "%#{search}%")
    else
      scoped
    end
  end

  def broadcast
    # TODO
  end
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  include ApplicationHelper
  before_filter :column_names
  helper_method :sort_column, :sort_direction
  
  # GET /histories
  # GET /histories.json
  def index
    @user = current_user
    if (params.has_key?(:user_id) && !params[:user_id].nil?)
      @histories = History.where("user_id="+ params[:user_id])
      if (params.has_key?(:sticker_id) && !params[:sticker_id].nil?)
        @histories += @histories.where("sticker_id="+ params[:sticker_id])
        if (params.has_key?(:location_id) && !params[:location_id].nil?)
          @histories += @histories.where("location_id="+ params[:location_id])
        end
      end
      @form_path = user_histories_path(User.find(params[:user_id]))
    else
      @histories = History.search(params[:search], params["column"]).reorder(sort_column + " " + sort_direction).paginate(:page => params[:page])
      @form_path = histories_path
    end

    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @histories }
    end
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
    @history = History.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/new
  # GET /histories/new.json
  def new
    @history = History.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @history }
    end
  end

  # GET /histories/1/edit
  def edit
    @history = History.find(params[:id])
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(params[:history])

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render json: @history, status: :created }
      else
        format.html { render action: "new" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /histories/1
  # PUT /histories/1.json
  def update
    @history = History.find(params[:id])

    respond_to do |format|
      if @history.update_attributes(params[:history])
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render json: @history, status: :ok }
        format.js
      else
        format.html { render action: "edit" }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history = History.find(params[:id])

    respond_to do |format|
      if @history
        @history.destroy
        format.html { redirect_to histories_url }
        format.json { render nothing: true, status: :ok }
      else
        format.html { redirect_to histories_url }
        format.json { render nothing: true, status: :not_found }
      end
    end
  end

  # ATTENTION
  def confirm
    @history = History.find(params[:id])

    respond_to do |format|
      if @history.update_attributes(:notification_confirmed => 1)
        format.html { redirect_to histories_url }
        format.json { render nothing: true, status: :ok }
      else
        format.html { redirect_to histories_url }
        format.json { render nothing: true, status: :not_found }
      end
    end
  end

  private

    def column_names
      @column_names = History.column_names
    end

    def sort_column
      History.column_names.include?(params[:sort]) ? params[:sort] : "created_at"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
    end
end

app/helpers/histories_helper.rb
module HistoriesHelper

	def get_user_notifications
		unless current_user.nil?
			@new_notifications = History.where("user_id=" + current_user.id.to_s + " AND notify=1 AND notification_confirmed=0")
			@old_notifications = History.where("user_id=" + current_user.id.to_s + " AND notify=1 AND notification_confirmed=1").limit(10)
		end
	end

	def dropdown_notifications
		@notifications = History.where("user_id=" + current_user.id.to_s + " AND notify=1 AND notification_confirmed=0")
	end

	# Web service

	def get_ws_user_new_notifications(user_id)
		web_service_url('users/' + user_id.to_s + '/new_notifications.json')
   		get_url
	    return parse_histories_from_parsed_json
	end

	def get_ws_user_old_notifications(user_id)
		web_service_url('users/' + user_id.to_s + '/old_notifications.json')
   		get_url
	    return parse_histories_from_parsed_json
	end

	def ws_confirm_notificaton(history_id)
		web_service_url('/histories/' + history_id.to_s + '/confirm.json')
		get_url
		return @parsed_json
	end

	def get_ws_stickers_total_histories_count(stickers)
		count = 0
		stickers.each do |s|
		    web_service_url('users/' + s.user_id.to_s + '/stickers/' + s.id.to_s + '/histories/count.json')
		    get_url
	    	count += @parsed_json
		end
	    return count
	end

	def get_ws_user_history(user_id, history_id, paginate = false, per_page = 10, page = 1)
	    web_service_url('users/' + user_id.to_s + '/histories/' + history_id.to_s + '.json')
	    get_url
	    history = parse_history_from_parsed_json(paginate, per_page, page)
	    return history
	end

	def get_ws_user_histories(user_id, paginate = false, per_page = 10, page = 1)
	    web_service_url('users/' + user_id.to_s + '/histories.json')
	    get_url
	    histories = parse_histories_from_parsed_json(paginate, per_page, page)
	    return histories
	end

	def get_ws_all_histories(paginate = false, per_page = 10, page = 1)
	    web_service_url('histories.json')
	    get_url
	    histories = parse_histories_from_parsed_json(paginate, per_page, page)
	    return histories
	end

	def parse_history_from_parsed_json(paginate = false, per_page = 10, page = 1)
	    history = History.new(@parsed_json)
	    history.id = @parsed_json['id']
	    return history
	end

	def parse_histories_from_parsed_json(paginate = false, per_page = 10, page = 1)
	    histories = Array.new
	    @parsed_json.each do |history, r|
	      h = History.new(history)
	      h.id = history['id']
	      histories.push(h)
	    end
	    histories = histories.paginate(:page => page, :per_page=> per_page) if paginate
	    return histories
	end

end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :subject %><br />
    <%= f.text_field :subject %>
  </div>
  <div class="field">
    <%= f.label :operation %><br />
    <%= f.text_field :operation %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :sticker_id %><br />
    <%= f.number_field :sticker_id %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.number_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/_histories.html.erb
<ul>
<% for history in @histories %>
	<li>
	  <%= render 'history_info_min', history: history, span_size: 12 %>
  </li>
<% end %>
</ul>

app/views/histories/_histories_table.html.erb
<%= render 'shared/search_navbar_top', models: @histories %>
<div id="histories" class="row-fluid">
	<%= render 'histories' %>
</div>
<%= render 'shared/search_navbar_bottom', models: @histories %>

app/views/histories/_history_info_min.html.erb
<% if (history.subject == 'sticker')
	sticker = Sticker.find(history.sticker_id) %>
	<%= history.created_at %>:
	<a href="<%= user_path(sticker.user.id) %>"><%= sticker.user.name %></a>  
	<%= history.operation %>
	<%= history.subject %>
	<%= link_to sticker.name, user_sticker_path(sticker.user, sticker) %>
<% end %>

<% if (history.subject == 'user')
	user = User.find(history.user_id) %>
	<%= history.created_at %>: 
	<a href="<%= user_path(user.id) %>"><%= user.name %></a>  
	<%= history.operation %>
<% end %>

<% if (history.subject == 'location')
	location = Location.find(history.location_id)
	sticker =Sticker.find(location.sticker_id)
	user = User.find(sticker.user_id) %>
	<%= history.created_at %>:
	<a href="<%= user_path(user.id) %>"><%= user.name %></a>:
	Located sticker
	<%= link_to sticker.name, user_sticker_path(user, sticker) %>
	at 
	<%= link_to location.latitude, user_sticker_location_path(user, sticker, location) %>, 
	<%= link_to location.longitude, user_sticker_location_path(user, sticker, location) %>.
<% end %>

<% if (history.subject == 'message')
	message = Message.find(history.message_id)
	user = User.find(message.from_user_id)
	to_user = User.find(message.user_id)
	%>
	<%= history.created_at %>:
	<%= link_to user.name, user_path(user.id) %>
	has sent a
	<%= link_to 'message', user_messages_path(user) %>
	to 
	<%= link_to to_user.name, user_path(to_user) %>
<% end %>
<br/>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<% provide(:title, 'All Events') %>

<div class="container-fluid page-content">
  <%= render 'shared/server_stats_header' %>

  <div id="histories-list" style="position:relative;top:-250px"></div>
		<h1>All events</h1>
	  <div class="well well-padding paper-shadow header-well">
			<%= render 'histories_table', histories: @histories %>
		</div>
</div>

<!-- Sidebar Fixed left -->
<% content_for :sidebar do %>
  <%= render 'users/friends' %>
  <h3>Navigate</h3>
  <ul id="sidebar-nav" class="nav nav-list affix" data-offset-top="200px">
    <li><a href="#histories-list" class="histories-list">Histories list</a></li>
  </ul>
<% end %>

app/views/histories/index.js.erb
$("#histories").html("<%= escape_javascript(render("histories")) %>");
$("#pagination-top").html("<%= escape_javascript(render("shared/navbar_pagination", models: @histories)) %>");
$("#pagination-bottom").html("<%= escape_javascript(render("shared/navbar_pagination", models: @histories)) %>");

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Subject:</b>
  <%= @history.subject %>
</p>

<p>
  <b>Operation:</b>
  <%= @history.operation %>
</p>

<p>
  <b>User:</b>
  <%= @history.user_id %>
</p>

<p>
  <b>Sticker:</b>
  <%= @history.sticker_id %>
</p>

<p>
  <b>Location:</b>
  <%= @history.location_id %>
</p>


<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>

app/views/histories/update.js.erb
$("#notifications_count").html("<%= get_ws_user_new_notifications(current_user.id).count %>");